# Generated by Django 5.1.4 on 2025-01-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_promocode_alter_user_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='promocode',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
