# Generated by Django 5.1.4 on 2025-01-22 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_otp_user_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_promo', to='accounts.promocode'),
        ),
    ]
