# Generated by Django 5.1.4 on 2025-01-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_promocode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='promocode',
        ),
        migrations.AddField(
            model_name='user',
            name='promocode',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='accounts.promocode'),
        ),
    ]
