# Generated by Django 5.1.4 on 2025-01-13 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_photo', models.ImageField(blank=True, null=True, upload_to='banner/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg'))])),
                ('banner_photo2', models.ImageField(blank=True, null=True, upload_to='banner/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg'))])),
                ('text1', models.CharField(blank=True, max_length=355, null=True)),
                ('text2', models.CharField(blank=True, max_length=355, null=True)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='photo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg'))])),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='photo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg'))])),
            ],
        ),
        migrations.CreateModel(
            name='ImageCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='carousel/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg'))])),
                ('image2', models.ImageField(blank=True, null=True, upload_to='carousel/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg'))])),
                ('image3', models.ImageField(blank=True, null=True, upload_to='carousel/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg'))])),
            ],
        ),
        migrations.CreateModel(
            name='PromoAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promo_response', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_alert', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='website/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'png'))])),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('whatsapp', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Utility',
                'verbose_name_plural': 'Utilities',
            },
        ),
    ]
