# Generated by Django 5.1.4 on 2025-01-09 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='carousel/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg'))])),
                ('image2', models.ImageField(upload_to='carousel/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg'))])),
                ('image3', models.ImageField(upload_to='carousel/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg'))])),
            ],
        ),
        migrations.AlterModelOptions(
            name='utility',
            options={'verbose_name': 'Utility', 'verbose_name_plural': 'Utilities'},
        ),
        migrations.AddField(
            model_name='utility',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utility',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utility',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='website/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'png'))]),
        ),
        migrations.AddField(
            model_name='utility',
            name='show_alert',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='utility',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='utility',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='utility',
            name='whatsapp',
            field=models.URLField(blank=True, null=True),
        ),
    ]
