# Generated by Django 5.1.4 on 2025-01-30 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='banner_photo',
            field=models.ImageField(blank=True, null=True, upload_to='banner/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))]),
        ),
        migrations.AlterField(
            model_name='about',
            name='banner_photo2',
            field=models.ImageField(blank=True, null=True, upload_to='banner/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))]),
        ),
        migrations.AlterField(
            model_name='about',
            name='main_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='photo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))]),
        ),
        migrations.AlterField(
            model_name='about',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='photo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))]),
        ),
        migrations.AlterField(
            model_name='about',
            name='text1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='text2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagecarousel',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='carousel/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))]),
        ),
        migrations.AlterField(
            model_name='imagecarousel',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='carousel/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))]),
        ),
        migrations.AlterField(
            model_name='imagecarousel',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='carousel/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))]),
        ),
        migrations.AlterField(
            model_name='utility',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='website/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpegpng'))]),
        ),
    ]
