# Generated by Django 5.1.4 on 2025-01-09 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_imagecarousel_alter_utility_options_utility_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecarousel',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='carousel/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg'))]),
        ),
        migrations.AlterField(
            model_name='imagecarousel',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='carousel/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg'))]),
        ),
        migrations.AlterField(
            model_name='imagecarousel',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='carousel/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg'))]),
        ),
    ]
