# Generated by Django 5.1.4 on 2025-01-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_alter_imagecarousel_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promo_response', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
