# Generated by Django 5.1.4 on 2025-01-10 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0004_promoad'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_photo', models.ImageField(blank=True, null=True, upload_to='banner/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg'))])),
                ('banner_photo2', models.ImageField(blank=True, null=True, upload_to='banner/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg'))])),
                ('text1', models.CharField(blank=True, max_length=355, null=True)),
                ('text2', models.CharField(blank=True, max_length=355, null=True)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='photo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg'))])),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='photo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg'))])),
            ],
        ),
    ]
