# Generated by Django 5.1.4 on 2025-01-30 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamplePack',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=125)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='combo_deals/', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'png'])])),
                ('original_price', models.FloatField(blank=True, default=0, null=True)),
                ('discount_rate', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discounted_price', models.FloatField(blank=True, default=0, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('weight', models.FloatField(default=0, editable=False)),
            ],
        ),
    ]
