# Generated by Django 5.1.4 on 2025-01-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotdealproducts',
            name='hot_deal_id',
        ),
        migrations.RemoveField(
            model_name='hotdealproducts',
            name='product',
        ),
        migrations.RenameField(
            model_name='combodeal',
            old_name='combo_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='hotdeal',
            old_name='hot_id',
            new_name='id',
        ),
        migrations.DeleteModel(
            name='ComboProducts',
        ),
        migrations.DeleteModel(
            name='HotDealProducts',
        ),
    ]
