# Generated by Django 5.1.4 on 2025-02-02 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0002_carthot_cartsample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_coupon', to='accounts.promocode'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
