# Generated by Django 5.1.4 on 2025-01-26 15:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cart_address_order_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotDeal',
            fields=[
                ('hot_deal_id', models.CharField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=125)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='hot_deals/', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'png'])])),
                ('original_price', models.FloatField(blank=True, default=0, null=True)),
                ('discount_rate', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discounted_price', models.FloatField(blank=True, default=0, null=True)),
                ('description', models.CharField(blank=True, null=True)),
                ('weight', models.FloatField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='HotDealProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hot_deal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_deal', to='products.hotdeal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_product', to='products.product')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Hot Deal Products',
            },
        ),
    ]
