# Generated by Django 5.1.4 on 2025-01-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_samplepack'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotdeal',
            options={'verbose_name': 'Hot Deal', 'verbose_name_plural': 'Hot Deals'},
        ),
        migrations.AlterModelOptions(
            name='samplepack',
            options={'verbose_name': 'Sample Pack', 'verbose_name_plural': 'Sample Packs'},
        ),
        migrations.AlterField(
            model_name='combodeal',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='hotdeal',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='samplepack',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
