# Generated by Django 5.1.4 on 2025-01-29 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address_delete_address'),
        ('products', '0003_alter_cart_address_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_coupon', to='accounts.promocode'),
        ),
        migrations.AddField(
            model_name='order',
            name='isCouponApplied',
            field=models.BooleanField(default=False),
        ),
    ]
