# Generated by Django 5.1.4 on 2025-01-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivered',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Placed', 'PLACED'), ('Shipped', 'SHIPPED'), ('Out for Delivery', 'OUT FOR DELIVERY'), ('Delivered', 'DELIVERED'), ('Cancelled', 'CANCELLED')], default='PENDING'),
        ),
    ]
