# Generated by Django 5.1.4 on 2025-01-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_order_delivered_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Placed', 'PLACED'), ('Shipped', 'SHIPPED'), ('Out for Delivery', 'OUT FOR DELIVERY'), ('Delivered', 'DELIVERED'), ('Cancelled', 'CANCELLED')], default='PENDING'),
        ),
    ]
