# Generated by Django 5.1.4 on 2025-01-29 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_order_coupon_id_order_iscouponapplied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='isCouponApplied',
            new_name='is_coupon_applied',
        ),
    ]
