# Generated by Django 5.1.4 on 2025-02-02 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_ordercombo_orderhot_ordersample'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordercombo',
            old_name='subtotal',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='orderhot',
            old_name='subtotal',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='ordersample',
            old_name='subtotal',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='ordercombo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_combo', to='products.combodeal'),
        ),
        migrations.AlterField(
            model_name='ordersample',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_sample', to='products.samplepack'),
        ),
    ]
