# Generated by Django 5.1.4 on 2025-01-09 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_cart_cartproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='qty',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
