# Generated by Django 5.1.4 on 2025-01-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Placed', 'PLACED'), ('Cancelled', 'CANCELLED')], default='Pending'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Placed', 'PLACED'), ('Shipped', 'SHIPPED'), ('Out for Delivery', 'OUT FOR DELIVERY'), ('Delivered', 'DELIVERED'), ('Cancelled', 'CANCELLED')], default='PLACED'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'PLACED'), ('Shipped', 'SHIPPED'), ('Out for Delivery', 'OUT FOR DELIVERY'), ('Delivered', 'DELIVERED'), ('Cancelled', 'CANCELLED')], default='PENDING'),
        ),
    ]
