# Generated by Django 5.1.4 on 2025-01-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_cartproduct_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='price',
            new_name='subtotal',
        ),
    ]
